package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IDebtRepository;
import dao.uow.IUnitOfWork;
import domain.model.Debt;



public class DebtRepository extends RepositoryBase <Debt> implements IDebtRepository {

	private PreparedStatement getUserId;
	
	public DebtRepository(Connection connection,
			IMapResultSetIntoEntity <Debt> mapper, IUnitOfWork uow) {
		super(connection,mapper, uow);
		try {
			getUserId = connection.prepareStatement(getUserIdSql());

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE debt("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "userId bigint," + "payment int(10)"  
				+")";
	}

	@Override
	protected String tableName() {
		return "debt";
	}

	@Override
	protected String insertSql() {
		// TODO Auto-generated method stub
		return "INSERT INTO debt (userId, payment) VALUES (?,?)";
	}

	@Override
	protected String updateSql() {
		// TODO Auto-generated method stub
		return "UPDATE debt SET (userId, payment)=(?,?) where id=?";
	}

	@Override
	protected void setUpdate(Debt entity) throws SQLException {
		// TODO Auto-generated method stub
		update.setInt(1, entity.getUserId());
		update.setBigDecimal(2, entity.getPayment());
		
		
	}

	@Override
	protected void setInsert(Debt entity) throws SQLException {
		// TODO Auto-generated method stub
		insert.setInt(1, entity.getUserId());
		insert.setBigDecimal(2, entity.getPayment());
	}

	protected String getUserIdSql() {
		// TODO Auto-generated method stub
		return "SELECT * FROM debt where userId = ?";
	}
	
	
}
