package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IDebtRepository;
import dao.uow.IUnitOfWork;
import domain.model.Debt;



public class DebtRepository extends RepositoryBase <Debt> implements IDebtRepository {

	private PreparedStatement getPatientCardId;
	
	public DebtRepository(Connection connection,
			IMapResultSetIntoEntity <Debt> mapper, IUnitOfWork uow) {
		super(connection,mapper, uow);
		try {
			getPatientCardId = connection.prepareStatement(getPatientCardIdSql());

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE debt("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "patientCardId bigint," + "payment int(10)"  
				+")";
	}

	@Override
	protected String tableName() {
		return "debt";
	}

	@Override
	protected String insertSql() {
		// TODO Auto-generated method stub
		return "INSERT INTO debt (patientCardId, payment) VALUES (?,?)";
	}

	@Override
	protected String updateSql() {
		// TODO Auto-generated method stub
		return "UPDATE debt SET (patientCardId, payment)=(?,?) where id=?";
	}

	@Override
	protected void setUpdate(Debt entity) throws SQLException {
		// TODO Auto-generated method stub
		update.setInt(1, entity.getPatientCardId());
		update.setBigDecimal(2, entity.getPayment());
		
		
	}

	@Override
	protected void setInsert(Debt entity) throws SQLException {
		// TODO Auto-generated method stub
		insert.setInt(1, entity.getPatientCardId());
		insert.setBigDecimal(2, entity.getPayment());
	}

	protected String getPatientCardIdSql() {
		// TODO Auto-generated method stub
		return "SELECT * FROM debt where patientCardId = ?";
	}


	public List<Debt> fromPatientCardId(int patientCardId) {
		// TODO Auto-generated method stub
		List <Debt> debt = new ArrayList<Debt>();
		try{
		getPatientCardId.setInt(1,patientCardId);
		ResultSet resultSet = getPatientCardId.executeQuery();
		while(resultSet.next()){
			debt.add(mapper.map(resultSet));
		}
		}
		catch (SQLException e)
		{
		e.printStackTrace();
		}
		return debt;
	}
	
	
}
