package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import domain.model.PatientCard;

public class PatientCardRepository extends BaseRepository {
	private String insertSql = "INSERT INTO patientCard (name, surname, birthDate, personalIdentityNumber, phoneNumber, email, roomId, status, historyOfDiseases, ailments) VALUES (?,?,?,?,?,?,?,?,?,?)";
	private String selectByIdSql = "SELECT * FROM patientCard WHERE id=?";
	private String deleteSql = "DELETE FROM patientCard WHERE id=?";
	private String getAllSql = "SELECT * FROM patientCard";
	
	PreparedStatement insert;
	PreparedStatement selectById;
	PreparedStatement delete;
	PreparedStatement getAll;
	
	public PatientCardRepository(Connection connection) {
		super(connection);
		try {
			insert = connection.prepareStatement(insertSql);
			selectById = connection.prepareStatement(selectByIdSql);
			delete = connection.prepareStatement(deleteSql);
			getAll = connection.prepareStatement(getAllSql);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public PatientCard get(int PatientCardId){
		try{
			selectById.setInt(1, PatientCardId);
			ResultSet rs = selectById.executeQuery();
			while(rs.next()){
				PatientCard result = new PatientCard();
				result.setId(rs.getInt("id"));
				result.setName(rs.getString("name"));
				result.setSurname(rs.getString("surname"));
				result.setBirthDate(rs.getDate("birthDate"));
				result.setPersonalIdentityNumber(rs.getString("personalIdentityNumber"));
				result.setPhoneNumber(rs.getString("phoneNumber"));
				result.setEmail(rs.getString("email"));
				result.setRoomId(rs.getInt("roomId"));
				//result.setStatus(rs.getString("status"));
				result.setHistoryOfDiseases(rs.getString("historyOfDiseases"));
				result.setAilments(rs.getString("Ailments"));
				
				return result;
			}
		}
		catch(SQLException ex){
			ex.printStackTrace();
		}
		return null;
		
	}
	
	public void add(PatientCard patientCard) {
		try {
			insert.setString(1, patientCard.getName());
			insert.setString(2, patientCard.getSurname());
			insert.setDate(3, patientCard.getBirthDate());
			insert.setString(4, patientCard.getPersonalIdentityNumber());
			insert.setString(5, patientCard.getPhoneNumber());
			insert.setString(6, patientCard.getEmail());
			insert.setInt(7, patientCard.getRoomId());
			//insert.setObject(8, patientCard.getStatus());
			insert.setString(9, patientCard.getHistoryOfDiseases());
			insert.setString(10, patientCard.getAilments());
			insert.executeUpdate();
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
	}

	public void delete(int patientCardId)
	{
		try {
			delete.setInt(1, patientCardId);
			delete.executeQuery();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
	}
	
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE patientCard("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(20)"  
				+ "birthDate DATE," + "personalIdentityNumber varchar(15),"
				+ "phoneNumber varchar(20)," + "email varchar (30),"
				+ "status varchar(20)," + "historyOfDiseases varchar (1000),"
				+ "ailments varchar (500)"
				+")";
	}

	@Override
	protected String tableName() {
		return "patientCard";
	}

	
	
}

